### ISSUE TITLE
Not set to SSL

### ISSUE THREAD

**Issue by cmarkwick365** [auth0-samples/auth0-aspnetcore-mvc-samples#88]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/tree/master/Quickstart/Sample#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The sample needs to default to SSL to be able to configure redirect URIs

### Reproduction

Currently the sample defaults to http instead of https.  Needs app.UseHttpsRedirection() added and a SSL port needs to be enabled in the launch settings,

**Comment by frederikprijck** [comment]
The sample is explicitly configured with http instead of https, even though we do recommend always enabling https.

You should be able to use http://localhost as a redirect_uri, can you elaborate what's not working for you?

**Comment by cmarkwick365** [comment]
The question is why does the sample not have HTTPS enabled out of the box?  It would be much easier to just clone the sample app without having to modify it to get it to work with HTTPS.

**Comment by frederikprijck** [comment]
Thanks for the feedback, and i don't disagree.

We are using http due to some internal automation tooling regarding our quickstarts that work for all technologies (you can download this sample through our quickstarts page and have all values filled in, and have your auth0 tenant be configured for u)

Even though it's easy for dotnet to enable HTTPS, it's not the case for other technologies.

I do agree we want to see if we can use https for all, or some. But for the time being, we will need to stick to HTTP.
